# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GsqlProxy < Formula
  desc ""
  homepage "https://github.com/KeyValueSoftwareSystems/homebrew-tools"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/KeyValueSoftwareSystems/gsql-proxy/releases/download/v1.0.0/gsql-proxy_1.0.0_Darwin_arm64.tar.gz"
      sha256 "db09ef31e3f91013c6d9a435105d9d2ac90d51f2caacf17d29561a112a6ba169"

      def install
        bin.install "gsql-proxy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/KeyValueSoftwareSystems/gsql-proxy/releases/download/v1.0.0/gsql-proxy_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "7c19cbd0525f9ee455a780784ed856b62046976bafab6444c8280fbc1d27cb51"

      def install
        bin.install "gsql-proxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/KeyValueSoftwareSystems/gsql-proxy/releases/download/v1.0.0/gsql-proxy_1.0.0_Linux_x86_64.tar.gz"
      sha256 "cd988b7034c62328962a790cefdf0213a93bf536821c1130e9a04b0124824bff"

      def install
        bin.install "gsql-proxy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KeyValueSoftwareSystems/gsql-proxy/releases/download/v1.0.0/gsql-proxy_1.0.0_Linux_arm64.tar.gz"
      sha256 "d998e00e14b9c1432fcfa3450bab98a3922236bebcda4862b9148d18908fe1d0"

      def install
        bin.install "gsql-proxy"
      end
    end
  end
end
